### ISSUE TITLE
Setup github dependabot

### ISSUE THREAD

**Issue by omonimus1** [rvVcNk2p/airdrop-farmer#3]

**Comment by rvVcNk2p** [comment]
So, the Dependabot alerts were already enabled. I have enabled the _Dependabot security updates_ section and configured the _.github/dependabot.yml_ file. (This is a required step to enabling the _Dependabot version updates_ functionality)

@omonimus1 If you are available, check out please the opened pull request.

1. I see the issue, that says: Add Dependabot to repo, but there is any checkpoint that I need to implement to accomplish the task?
2. What else do I need to add to my dependabot.yml file? Are there any missing options?
