### ISSUE TITLE
Set up gitguardian

### ISSUE THREAD

**Issue by omonimus1** [rvVcNk2p/airdrop-farmer#30]
https://www.gitguardian.com/?utm_feeditemid=&utm_device=c&utm_term=gitguardian%20github&utm_source=bing&utm_medium=ppc&utm_campaign=&hsa_cam=403785777&hsa_grp=1344703324736541&hsa_mt=p&hsa_src=o&hsa_ad=&hsa_acc=5867098142&hsa_net=adwords&hsa_kw=gitguardian%20github&hsa_tgt=kwd-84045084233312:loc-188&hsa_ver=3&utm_adgroupid=1344703324736541&hsa_acc=5867098142&hsa_cam=10399074694&hsa_grp=1344703324736541&hsa_ad=&hsa_src=o&hsa_tgt=kwd-84045084233312:loc-188&hsa_kw=gitguardian%20github&hsa_mt=p&hsa_net=adwords&hsa_ver=3&msclkid=6c199131119c1747c600f4a7ddcb5ac7&utm_source=bing&utm_medium=cpc&utm_campaign=EU%20US%20%7C%20GitGuardian%20Brand&utm_term=gitguardian%20github&utm_content=GG%20Brand%20Phrase

**Comment by rvVcNk2p** [comment]
GitGuardian already implemented, and runs on every PR.

For example: https://github.com/rvVcNk2p/airdrop-farmer/runs/20117358848
